//
//  MainSearchPresenter.swift
//  AppSearch
//
//  Created by 기민주 on 2021/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSearchPresentationLogic
{
	func presentSomething(response: MainSearch.Something.Response)
}

class MainSearchPresenter: MainSearchPresentationLogic
{
	weak var viewController: MainSearchDisplayLogic?
	
	// MARK: Do something
	
	func presentSomething(response: MainSearch.Something.Response)
	{
		let viewModel = MainSearch.Something.ViewModel()
		viewController?.displaySomething(viewModel: viewModel)
	}
}
