//
//  MainSearchInteractor.swift
//  AppSearch
//
//  Created by 기민주 on 2021/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSearchBusinessLogic {
	func doSomething(request: MainSearch.Something.Request)
}

protocol MainSearchDataStore {
	var name: String { get set }
}

class MainSearchInteractor: MainSearchBusinessLogic, MainSearchDataStore {
	var presenter: MainSearchPresentationLogic?
	var worker: MainSearchWorker?
	var name: String = ""

	// MARK: Do something
	
	func doSomething(request: MainSearch.Something.Request) {
		worker = MainSearchWorker()
		worker?.doSomeWork()

		let response = MainSearch.Something.Response()
		presenter?.presentSomething(response: response)
	}
}
