//
//  MainSearchRouter.swift
//  AppSearch
//
//  Created by 기민주 on 2021/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainSearchRoutingLogic
{
	//func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol MainSearchDataPassing
{
	var dataStore: MainSearchDataStore? { get }
}

class MainSearchRouter: NSObject, MainSearchRoutingLogic, MainSearchDataPassing
{
	weak var viewController: MainSearchViewController?
	var dataStore: MainSearchDataStore?
	
	// MARK: Routing
	
	//func routeToSomewhere(segue: UIStoryboardSegue?)
	//{
	//  if let segue = segue {
	//    let destinationVC = segue.destination as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//  } else {
	//    let storyboard = UIStoryboard(name: "Main", bundle: nil)
	//    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//    navigateToSomewhere(source: viewController!, destination: destinationVC)
	//  }
	//}
	
	// MARK: Navigation
	
	//func navigateToSomewhere(source: MainSearchViewController, destination: SomewhereViewController)
	//{
	//  source.show(destination, sender: nil)
	//}
	
	// MARK: Passing data
	
	//func passDataToSomewhere(source: MainSearchDataStore, destination: inout SomewhereDataStore)
	//{
	//  destination.name = source.name
	//}
}
