//
//  MainSearchPresenter.swift
//  AppSearch
//
//  Created by 기민주 on 2021/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSearchPresentationLogic {
	func presentInquiryResult(response: MainSearch.Response)
	func presentRecent(response: SearchedModel.Response)
}

class MainSearchPresenter: MainSearchPresentationLogic {

	weak var viewController: MainSearchDisplayLogic?

	// Do present Data Customize example Formatting

	func presentRecent(response: SearchedModel.Response) {
		let data = response.searchedList ?? [""]
		let viewModel = SearchedModel.ViewModel(searchedList: data)
		viewController?.displayRecent(viewModel: viewModel)
	}

	func presentInquiryResult(response: MainSearch.Response) {
		let viewModel = MainSearch.ViewModel(listCount: response.inquiry?.resultCount, displayedResult: response.inquiry?.list ?? [] )
		viewController?.displaySomething(viewModel: viewModel)
	}
}
