//
//  MainSearchInteractor.swift
//  AppSearch
//
//  Created by 기민주 on 2021/03/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol MainSearchBusinessLogic {
	func doSearch(request: MainSearch.Request)
	func getRecentData()
}

class MainSearchInteractor: MainSearchBusinessLogic {

	var presenter: MainSearchPresentationLogic?
	private var worker: MainSearchWorker?
	private var localDataWorker = LocalDataWorker()

	// MARK: Data Request and Valid Request Data

	/// 최근 기록 가져오기
	func getRecentData() {
		localDataWorker.getData(completion: { [weak self] data in
			guard let `self` = self else { return }
			self.presenter?.presentRecent(response: data)
		})
	}

	/// 검색 하기
	func doSearch(request: MainSearch.Request) {
		localDataWorker.setRecordCoreData(addData: request.searchText) // 검색어 저장
		worker = MainSearchWorker()
		worker?.doSearch(request: request, completion: { [weak self] data in
			guard let `self` = self else { return }
			let response = MainSearch.Response(inquiry: data)
			self.presenter?.presentInquiryResult(response: response)
		})
	}
}
